#ifndef LIB_REACT_BRAIN
#define LIB_REACT_BRAIN

#include <LIB_LEDC.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_err.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include <esp_log.h>
#include "driver/adc.h"
#include "esp_adc_cal.h"
#include "driver/gpio.h"

#define LIGHT_SENSOR_1_PIN ADC1_CHANNEL_4
#define LIGHT_SENSOR_2_PIN ADC1_CHANNEL_5
#define SOUND_SENSOR_1_PIN ADC1_CHANNEL_6
#define SOUND_SENSOR_2_PIN ADC1_CHANNEL_7

/*RIGHT BRAIN DEFINES*/
#define RIGHT_VISUAL_CORTEX_1_PIN GPIO_NUM_2
#define RIGHT_VISUAL_CORTEX_2_PIN GPIO_NUM_4
#define RIGHT_AUDITORY_CORTEX_1_PIN GPIO_NUM_5
#define RIGHT_AUDITORY_CORTEX_2_PIN GPIO_NUM_12
#define RIGHT_STANDART_1_PIN GPIO_NUM_13 //PNP
#define RIGHT_STANDART_2_PIN GPIO_NUM_14
#define RIGHT_STANDART_3_PIN GPIO_NUM_15
#define RIGHT_STANDART_4_PIN GPIO_NUM_18

/*LEFT BRAIN DEFINES*/
#define LEFT_VISUAL_CORTEX_1_PIN GPIO_NUM_19
#define LEFT_VISUAL_CORTEX_2_PIN GPIO_NUM_21
#define LEFT_AUDITORY_CORTEX_1_PIN GPIO_NUM_22
#define LEFT_AUDITORY_CORTEX_2_PIN GPIO_NUM_23
#define LEFT_STANDART_1_PIN GPIO_NUM_25
#define LEFT_STANDART_2_PIN GPIO_NUM_26
#define LEFT_STANDART_3_PIN GPIO_NUM_17
#define LEFT_STANDART_4_PIN GPIO_NUM_16

/*DUTY DEFINES*/
#define DUTY_LOW 65534/2
#define DUTY_HIGH 65535

/*SENSORS DEFINES*/
#define LIGHT_SENSE 40
#define SOUND_SENSE 90

/*TASK DEFINES*/
#define REACT_BRAIN_TASK_TAG "LIB_REACT_BRAIN TASK"
#define REACT_BRAIN_TASK_STACK 1024*2
static TaskHandle_t REACT_BRAIN_TASK_HANDLE = NULL;

/*FUNCTIONS*/
void react_brain_init();


#endif